name: 'Install OpenWatcom 1.9'
description: 'Install OpenWatcom 1.9 development tools'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      id: cache-ow19-target
      with:
        path: |
          watcom/h/**/*
          watcom/lib/**/*
        key: ow19target
    - uses: actions/cache@v2
      id: cache-ow19-host
      with:
        path: watcom/bin*/*
        key: ow19host-${{ runner.os }}
    - run: |
        archive_sha1=98ee451bdda51736d279c5655101145f9ff364ac
        if [ ${{ runner.os }} == Linux ]
        then
          primary_bindir=binl
          secondary_bindir=binw
          exeext=
        fi
        if [ ${{ runner.os }} == Windows ]
        then
          primary_bindir=binnt
          secondary_bindir=binw
          exeext=.exe
        fi
        [ -f "$GITHUB_WORKSPACE"/watcom/lib286/dos/clibc.lib ] && [ -f "$GITHUB_WORKSPACE"/watcom/$primary_bindir/wcc${exeext} ] || {
            curl -L https://github.com/open-watcom/open-watcom-1.9/releases/download/ow1.9/open-watcom-c-linux-1.9 > '${{ runner.temp }}'/install
            actual_sha1=$(sha1sum '${{ runner.temp }}'/install | cut -c 1-40)
            if ! [ $actual_sha1 == $archive_sha1 ]
            then
              echo open-watcom-c-linux-1.9 download has sha1 $actual_sha1, expected $archive_sha1
              exit 1
            fi
            pushd '${{ runner.temp }}'
            mkdir stage
            cd stage
            unzip -q ../install
            mkdir -p "$GITHUB_WORKSPACE"/watcom
            mv $primary_bindir $secondary_bindir h lib286 lib386 "$GITHUB_WORKSPACE"/watcom/
            popd  
        }
        [ -d "$GITHUB_WORKSPACE"/watcom/binl ] && {
            pushd "$GITHUB_WORKSPACE"/watcom/binl
            ls -1 | grep -v '\.' | xargs chmod 755
            popd
        }
        echo "$GITHUB_WORKSPACE"/watcom/$primary_bindir >> $GITHUB_PATH
        [ -n "$secondary_bindir" ] && echo "$GITHUB_WORKSPACE"/watcom/$secondary_bindir >> $GITHUB_PATH
        echo INCLUDE="$GITHUB_WORKSPACE"/watcom/h >> $GITHUB_ENV
        echo WATCOM="$GITHUB_WORKSPACE"/watcom >> $GITHUB_ENV
      shell: 'bash'
